lib/source/chat/messages_state.dart
lib/source/chatlist/chat_list_item.dart
lib/source/chatlist/create_chat.dart
lib/source/chatlist/create_group_chat.dart
lib/source/data/chat_list_repository.dart
lib/source/log/bloc_delegate.dart
lib/source/login/login_bloc.dart
lib/source/main/root.dart
lib/source/profile/edit_user_settings.dart
pubspec.yaml

Updated everything as good as possible and also removed unneeded code.

Update libraries and clean up warnings #3 OT-115

---

lib/main.dart
lib/src/chat/chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_invite_item.dart
lib/src/chatlist/chat_list_item.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/selectable_contact_item.dart
lib/src/data/config.dart
lib/src/l10n/localizations.dart
lib/src/login/login.dart
lib/src/login/login_bloc.dart
lib/src/maillist/mail_list_item.dart
lib/src/message/message_item.dart
lib/src/profile/edit_account_settings.dart
lib/src/profile/edit_user_settings.dart
lib/src/profile/profile.dart
lib/src/utils/colors.dart
lib/src/utils/dimensions.dart
lib/src/utils/styles.dart
lib/src/widgets/avatar.dart
lib/src/widgets/avatar_list_item.dart
lib/src/widgets/dialog_builder.dart
lib/src/widgets/progress_handler.dart

- Use dimension class where possible
- Use localization class where possible
- Use color class where possible
- Created https://github.com/open-xchange/ox-talk/compare/OT-83?expand=1#diff-3c86de7f500e808aa089865e6f8c3866 to avoid code duplication
- Clean up
- Enforce config reload after login to ensure all values are successfully set
Tried to remove all direct calls to strings, colors, dimensions an styles.

OT-83 Use dimensions class

---

lib/main.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_invite_item.dart
lib/src/chatlist/chat_list_item.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/main/root.dart
lib/src/navigation/navigation.dart
lib/src/profile/edit_account_settings.dart
lib/src/profile/edit_user_settings.dart
lib/src/profile/profile.dart
lib/src/widgets/dialog_builder.dart

Added the new Navigation class and added animation for tab switching on main page

OT-70 Implement navigator based navigation pattern

---

lib/main.dart
lib/src/l10n/core_localitazions.dart
lib/src/l10n/localizations.dart

New core version with new handling, e.g for strings.
The app sets the strings now in the core. This way we avoid reloading / fetch data over and over, but the client stays in control of the strings.

OT-85 Update ApplicationDcContext to latest core

---

lib/main.dart
lib/src/contact/contact_list.dart
lib/src/l10n/localizations.dart
lib/src/main/main_bloc.dart
lib/src/main/main_event.dart
lib/src/main/main_state.dart
lib/src/navigation/navigation.dart
lib/src/utils/dialog_builder.dart
lib/src/widgets/root_view_switcher.dart

The main.dart file does not contain BloC logic.
- Added main_bloc.dart
- Clean up of the main.dart
- Moved dialog_builder.dart
- Created root_view_switcher.dart

OT-101 Convert main.dart to BloC pattern

---

lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/chatlist/chat_list_invite_item.dart
lib/src/chatlist/chat_list_state.dart
lib/src/chatlist/chat_list_view.dart
lib/src/chatlist/invite_list.dart
lib/src/l10n/localizations.dart
lib/src/main/root.dart
lib/src/message/messages_bloc.dart
pubspec.yaml

https://github.com/open-xchange/ox-talk/issues/22
We have two tabs in the ChatListView (Chats | Invites). 
Added a TabBar with two TabBarViews.
At the moment it is not possible to set an indicator for new invites.

Create new chat/invite view #22

---

lib/src/chat/chat.dart
lib/src/chat/chat_profile_view.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list_invite_item.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_change_bloc.dart
lib/src/contact/contact_change_event.dart
lib/src/contact/contact_import_bloc.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_item_bloc.dart
lib/src/contact/contact_list.dart
lib/src/contact/contact_list_bloc.dart
lib/src/contact/contact_list_event.dart
lib/src/data/contact_repository.dart
lib/src/data/repository_manager.dart
lib/src/l10n/localizations.dart
lib/src/message/message_item_bloc.dart
lib/src/navigation/navigation.dart

https://github.com/open-xchange/ox-talk/issues/35
It was not possible to block a contact from the ChatView and there was no way to unblock a contact,
I Added a first implementation of the ChatProfileView to block a contact and there is a ContactBlockList reachable over a button from the contact list. In this list we have all blocked contacts and by tapping on a blocked contact the user can unblock this contact.
Removed unused imports and we use three different types of contact repositories (valid, invites & blocked)

added blocking and unblocking of contacts OT-140 #35

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/src/chat/chat.dart
lib/src/chat/chat_composer.dart
lib/src/chat/chat_composer_bloc.dart
lib/src/chat/chat_composer_event.dart
lib/src/chat/chat_composer_state.dart
lib/src/contact/contact_import_bloc.dart
lib/src/data/repository_stream_handler.dart
lib/src/l10n/localizations.dart
lib/src/message/message_item_bloc.dart
lib/src/utils/security.dart
pubspec.yaml

#41 
Adding voice messages, images and videos recorded within the app is now possible.

OT-147 Add voice and video messages #41

---

lib/src/l10n/localizations.dart
lib/src/message/message_item.dart

#53 
Added the required methods. Flutter provides direct access to the clipboard, no external libraries are needed.

Message Actions - Copy #53 OT-158

---

lib/src/contact/contact_list.dart
lib/src/contact/contact_list_bloc.dart
lib/src/contact/contact_list_event.dart
lib/src/l10n/localizations.dart
lib/src/message/message_item.dart

#59 
Filtering in the contact list is now possible.
Added new events and states to allow filtering.
Only the commit https://github.com/open-xchange/ox-talk/commit/d780f12cc1853afefacf2211492cd24cc488011b is relevant, the other one belongs to #53 . I just based this on the wrong branch. Should be no problem if #53 is merged first.

 Add search / filtering for the contact list #59 OT-104

---

lib/src/chat/chat.dart
lib/src/chat/chat_composer_bloc.dart
lib/src/l10n/localizations.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_state.dart
lib/src/message/messages_bloc.dart
lib/src/message/messages_event.dart
lib/src/message/messages_state.dart
lib/src/utils/colors.dart
lib/src/utils/date.dart
lib/src/utils/styles.dart

Adjust time indicator in chat view #7 OT-117

---

lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event.dart
lib/src/chat/chat_state.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/chatlist/chat_list_item.dart
lib/src/data/chat_repository.dart
lib/src/l10n/localizations.dart
lib/src/utils/date.dart
lib/src/widgets/avatar_list_item.dart

https://github.com/open-xchange/ox-talk/issues/55
There was no date and no preview of the last received message in the ChatList.
Added the time and the preview to the ChatList by using the ChatSummary.
If there is an unread message than the time is bold as shown in the designs.

Show last message preview in the chat list #55

---

lib/src/chat/chat_composer_bloc.dart

Set audio recording type to mono #76 OT-174

---

lib/src/main/main_bloc.dart

Set accepted message type to chat only #78 OT-175

---

lib/main.dart
lib/src/chat/chat_profile_group_contact_item.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat_participants.dart
lib/src/chat/create_group_chat_settings.dart
lib/src/chatlist/invite_list.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/contact_item_chip.dart
lib/src/contact/contact_list.dart
lib/src/contact/contact_search_controller_mixin.dart
lib/src/contact/selectable_contact_item.dart
lib/src/l10n/localizations.dart
lib/src/utils/colors.dart
lib/src/utils/styles.dart
lib/src/widgets/avatar_list_item.dart
lib/src/widgets/search_field.dart

Fixed #60 and #61
Search / filtering for adding chats and groups chats was added. Also tried to adjust the UI to fit the given designs a bit more. They still differ, as there is some additional discussion needed, but some improvements where made.

Add search / filtering #60 #61 OT-105 OT-106

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_single_view.dart
lib/src/chat/chat_profile_view.dart
lib/src/chat/chat_state.dart
lib/src/contact/contact_item_bloc.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/contact_item_event.dart
lib/src/contact/contact_item_state.dart
lib/src/widgets/avatar_list_item.dart

https://github.com/open-xchange/ox-talk/issues/88
It was not possible to see if a chat is verified or not.
If there is a verified chat than we show an icon in the ChatList, in the chat header and in the ChatProfileView
I also implemented the verified icon for verified contacts.

Show if chat is verified #88 OT-190

---

lib/src/chat/chat_change_bloc.dart

#90 
Only the "missing contacts" problem was relevant. All other issues based on changed setups, which is fine.

OT-191 Group invite problems #90

---

android/app/build.gradle
android/app/google-services.json
android/app/src/main/AndroidManifest.xml
android/build.gradle
lib/main.dart
lib/src/notifications/notification_manager.dart
pubspec.yaml

https://github.com/open-xchange/ox-talk/issues/87
Added NotificationManager to setup/show local and push notifications. For push notifications we use Firebase. Added functions like showSingleNotifications, showGroupNotifications and cancel a specific or all notifications.
Grouping is not working correctly.

Added NotificationManager for local and push #87 OT-189

---

lib/main.dart
lib/src/chat/chat_create_group_settings.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_single_view.dart
lib/src/chatlist/chat_list_parent.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_list.dart
lib/src/l10n/localizations.dart
lib/src/login/login.dart
lib/src/navigation/navigation.dart
lib/src/platform/files.dart
lib/src/settings/settings_security.dart
lib/src/settings/settings_security_bloc.dart
lib/src/settings/settings_security_event.dart
lib/src/settings/settings_security_state.dart
lib/src/settings/settings_view.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/user/user_settings.dart
lib/src/utils/dimensions.dart
lib/src/utils/styles.dart
lib/src/widgets/progress_handler.dart
lib/src/widgets/validatable_text_form_field.dart
pubspec.yaml

#68 
- Changed the general settings setup
- Moved the account settings to the new settings menu
- Created the security settings menu
- Added key export / import to the security settings
- Also did some naming fixes in regards to our navigation class

OT-169 Key Handling - Export / import keys #68

---

lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_item.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/l10n/localizations.dart
lib/src/message/message_item.dart
lib/src/share/share.dart
lib/src/share/share_bloc.dart
lib/src/share/share_event.dart
lib/src/share/share_state.dart

https://github.com/open-xchange/ox-talk/issues/51
When the user taps on a text message or long pressed an attachment message, a popup menu is shown with different actions (copy, forward)
Added showMenu method with specified actions and added the function and screen to share/forward a message

Message Actions - Forward #51 OT-156

---

lib/src/l10n/localizations.dart
lib/src/navigation/navigation.dart
lib/src/settings/settings_about.dart
lib/src/settings/settings_about_bloc.dart
lib/src/settings/settings_about_event.dart
lib/src/settings/settings_about_state.dart
lib/src/settings/settings_view.dart
lib/src/widgets/UrlTextSpan.dart
pubspec.yaml

#102 
Added the about screen. Added url_launcher package to allow opening of browser links.

OT-208 Add about screen #102

---

lib/main.dart
lib/src/chat/chat_profile_single_view.dart
lib/src/chatlist/chat_list_item.dart
lib/src/main/root.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/notifications/notification_manager.dart

Just a small cleanup and one adjustment (https://github.com/open-xchange/ox-coi/compare/OT-214?expand=1#diff-5fe772f9d2183d2cff78acbbc5513f0c) to be able to use the latest plugin fixes.

OT-214 Allow updating of objects created by DCC

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event.dart
lib/src/data/chat_message_repository.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_state.dart
lib/src/message/message_list_bloc.dart

https://github.com/open-xchange/ox-coi/issues/70
It was not possible to see if a message was sent or read.
Added functionality to update the message state if it is changed and than show a specific icon for delivered and read.

Display message state #70

---

lib/src/message/message_item.dart

Message actions are sometimes broken #109

---

lib/src/message/message_builder_mixin.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_state.dart
lib/src/message/message_received_view.dart
lib/src/message/message_sent_view.dart
lib/src/message/message_special_view.dart
lib/src/utils/dimensions.dart

https://github.com/open-xchange/ox-coi/issues/101
It was not possible to detect if a message is encrypted.
Added a padlock icon next to the time indicator when the message is encrypted.

Show encryption status for chat messages #101 OT-207

---

lib/src/message/message_builder_mixin.dart
lib/src/message/message_received_view.dart
lib/src/message/message_sent_view.dart

Encryption icon is missing for attachment messages #126 OT-227

---

lib/src/chat/chat.dart
lib/src/chat/chat_create_group_settings.dart
lib/src/chat/chat_create_mixin.dart
lib/src/chat/chat_profile.dart
lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/chatlist/chat_list_parent.dart
lib/src/chatlist/invite_item.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_change_bloc.dart
lib/src/contact/contact_details.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_profile_mixin.dart
lib/src/l10n/localizations.dart
lib/src/navigation/navigatable.dart
lib/src/settings/settings_chat.dart
lib/src/utils/dimensions.dart
lib/src/widgets/avatar.dart
lib/src/widgets/profile_header.dart
pubspec.yaml

#118
- Added ContactProfile to actually fix this ticket
- Added ProfileHeader and ContactProfileMixing to unify profile creation
- Used ProfileHeader and ContactProfileMixing for the single and group chat profile view and also for the contact profile view
- Optimized the profile view UI (added icons, adjusted paddings and switched from Cards to ListTiles
- Added ChatCreateMixing to avoid code duplication
- Fixed some localizations
- Fixed wrong naming of chat settings (mentioned by Robert in the chat)
- Fixed #123 
- Fixed an error when changing a contact if no chat exists for that contact (unknown until now)
- Renamed multiple classes (they had the "view" suffix but weren't …

show profile view when selecting a contact #118 OT-222

---

lib/src/l10n/localizations.dart
lib/src/login/login.dart
lib/src/message/message_item.dart
lib/src/navigation/navigatable.dart
lib/src/qr/qr.dart
lib/src/qr/qr_bloc.dart
lib/src/qr/qr_event_state.dart
lib/src/qr/scan_qr.dart
lib/src/qr/show_qr.dart
lib/src/settings/settings_security.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/widgets/progress_handler.dart
pubspec.yaml

https://github.com/open-xchange/ox-coi/issues/69
It was not possible to verify users via QR code.
Added a QR button in the profile view which leads to a tab view with the user QR code and a tab to scan a QR code.

Key Handling - QR code verification #69

---

lib/src/data/repository.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart

https://github.com/open-xchange/ox-coi/issues/135
It was not possible to delete a message locally
Added a 'Delete locally' option to the message actions

Delete messages #135

---

lib/src/contact/contact_profile_mixin.dart
lib/src/debug/debug_viewer.dart
lib/src/debug/debug_viewer_bloc.dart
lib/src/debug/debug_viewer_event_state.dart
lib/src/l10n/localizations.dart
lib/src/log/log_bloc_delegate.dart
lib/src/log/log_manager.dart
lib/src/login/login_provider_list.dart
lib/src/message/message_item.dart
lib/src/navigation/navigatable.dart
lib/src/navigation/navigation.dart
lib/src/notifications/notification_manager.dart
lib/src/platform/files.dart
lib/src/settings/settings_chat.dart
lib/src/settings/settings_debug.dart
lib/src/settings/settings_debug_bloc.dart
lib/src/settings/settings_debug_event_state.dart
lib/src/settings/settings_security.dart
lib/src/settings/settings_view.dart
lib/src/utils/clipboard.dart

Added a debug view, debug settings and the ability to display raw data of received push messages. 
- Added settings_debug and corresponding classes to display debug information
- For now the push token can be found there
- Added debug_viewer and corresponding classes to display any information or the latest log file if no input is given
- Adjusted the notification_manager to display the received push message data in the debug_viewer
- Debug information is only available if the build is no release
- Added clipboard.dart to avoid code duplication
- Adjusted the logging of state changes

OT-247 Add push debug information

---

lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/repository.dart
lib/src/message/message_list_bloc.dart

Now delegating events also to registered listeners outside of the repositories. Also renamed some listeners.

OT-255 Delegate event to repository stream handler

---

lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/repository_stream_handler.dart
lib/src/login/login_bloc.dart
lib/src/message/message_list_bloc.dart
lib/src/notifications/local_push_manager.dart
lib/src/qr/qr_bloc.dart
lib/src/settings/settings_security_bloc.dart

- Added clean up methods for the repository stream handler
- Added missing guards to avoid double registration of listeners
- Small naming things
- Unset listener ids after tear down / removing of listeners

OT-256 Verify amount of registered listeners throughout the app

---

lib/src/chatlist/chat_list.dart
lib/src/data/chat_message_repository.dart
lib/src/flagged/flagged.dart
lib/src/flagged/flagged_bloc.dart
lib/src/flagged/flagged_events_state.dart
lib/src/l10n/localizations.dart
lib/src/message/message_action.dart
lib/src/message/message_change_bloc.dart
lib/src/message/message_change_event_state.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart
lib/src/message/message_received_view.dart
lib/src/message/message_sent_view.dart

https://github.com/open-xchange/ox-coi/issues/134
It was not possible to flag a message and see it in a special view
Flag method added in context menu and special flagged view is reacheable over the star button in the chatlist.

Flag messages #134 OT-240

---

lib/src/login/login_manual_settings.dart

#148
Moved the sign in button out of the scroll view.

OT-264 Dont scroll the sign in button #148

---

lib/src/chatlist/invite_item.dart
lib/src/flagged/flagged.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_list.dart
lib/src/login/login_provider_signin.dart
lib/src/message/message_item.dart
lib/src/settings/settings_manual_mixin.dart
lib/src/user/user_account_settings.dart

https://github.com/open-xchange/ox-coi/issues/149
The new manual settings view was not edited in the settings.
Changed the screen and Added a mixin to decrease code duplication.
Removed unused imports

Use the same advanced view in the settings #149

---

lib/src/chatlist/invite_item.dart
lib/src/flagged/flagged.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_list.dart
lib/src/login/login_provider_signin.dart
lib/src/main/root.dart
lib/src/message/message_item.dart
lib/src/settings/settings_manual_mixin.dart
lib/src/user/user_account_settings.dart

https://github.com/open-xchange/ox-coi/issues/157
After pressing the pysical back button the app closed on every selected tab in the root view.
Now the app is only closed on the chatlist tab and pressing the button on the other tabs brings the user to the chatlist.

Handle back on the main screen #157

---

.gitignore
lib/src/login/login_provider_signin.dart
pubspec.yaml
test_driver/app.dart
test_driver/app_test.dart

Added integration tests for the login flow.
Added the screenshots directory to the .gitignore file.

OT-280 Add integration tests for the login screen

---

lib/src/chat/chat_create_group_settings.dart

#182
Expanded the scroll area around all components.

OT-324 UI errors on group creation #182

---

lib/src/contact/contact_details.dart
lib/src/main/main_bloc.dart

OT-323 Contact name not changed + ME email empty on inital start #178

---

lib/src/chat/chat_composer_mixin.dart

#185 #186
Enabled line breaks and allowed the input text field to grow to a maximum of 4 lines.

OT-327 OT-332 Optimize chat composer #185 #186

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/openxchange/oxcoi/Application.java
documentation/licenses.csv
pubspec.yaml

Added the background_fetch library and tested it on Android (refresh while within the app and while the app was closed via back button). Both worked well, so the actual feature implementation (see #121) can start.

OT-314 Background refresh via background_fetch

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/openxchange/oxcoi/MainActivity.java
android/app/src/main/java/com/openxchange/oxcoi/ShareHelper.java
lib/main.dart
lib/src/chat/chat.dart
lib/src/chatlist/chat_list.dart
lib/src/message/message_item.dart
lib/src/message/message_list_bloc.dart
lib/src/message/message_list_event_state.dart
lib/src/share/share.dart
lib/src/share/share_bloc.dart
lib/src/share/shared_data.dart

[Internal tracker](https://jira.open-xchange.com/browse/OT-108)
It was not possible to share data with the app (platform to app)
Added the needed Intent-filter and saved a copy of the file to the app cache. This file is deleted when the user sends the message or canceled the action.

OT-108 Allow sharing via OX Coi (Platform to app)

---

lib/src/widgets/profile_body.dart

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-375)
Wrong placement of translations.
Added the right placement.

Truncated text when deleting chat OT-375

---

lib/src/chat/chat.dart

https://jira.open-xchange.com/browse/OT-433
Hide telephone icon in groups.

OT-433 Remove telephone action from groups

---

assets/html/privacypolicy.html
assets/html/terms.html
lib/src/login/login.dart
lib/src/web/web_asset.dart
lib/src/web/web_asset_bloc.dart
lib/src/web/web_asset_event_state.dart
lib/src/widgets/url_text_span.dart
pubspec.yaml

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-263)
The links in the login screen are not clickable.
Added a privacy screen to show the "terms & conditions" or "privacy policy" html file.

OT-263 Legal URLs

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_change_bloc.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/notifications/local_push_manager.dart

[Internal Bug tracker](https://jira.open-xchange.com/browse/OT-420)
Messages from known contacts are shown as invites and not as chat.
We create a chat when a message of a known contact comes in.

OT-420 messages of known contacts are shown as invite and not as chat

---

android/app/build.gradle
lib/src/data/repository.dart

https://jira.open-xchange.com/browse/OT-458
Check if the item is not null before trying to access member variables.
Fixed a build error.

OT-458 Fix exception and build problems

---

lib/src/chatlist/chat_list_bloc.dart

[Internal Bug Tracker]()
Chat list flickers when receiving message.
Removed unnecessary setting of ChatSummary.

OT-422 Chat list flickers when receiving message

---

lib/src/qr/qr_bloc.dart

#218 and https://jira.open-xchange.com/browse/OT-472
The contact which is verified wasn't added to the repository.
Added the contact.

OT-472 Unlimited spinner after QR verification

---

ios/Podfile.lock
lib/src/antiMobbing/anti_mobbing_list_bloc.dart
lib/src/chat/chat_bloc.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/repository.dart
lib/src/data/repository_stream_handler.dart
lib/src/login/login_bloc.dart
lib/src/message/message_list_bloc.dart
lib/src/notifications/local_push_manager.dart
lib/src/push/push_bloc.dart
lib/src/qr/qr_bloc.dart
lib/src/settings/settings_security_bloc.dart
lib/src/widgets/fullscreen_progress.dart

[Internal Issue: OT-487](https://jira.open-xchange.com/browse/OT-487)

OT-487: Verify event handling is working

---

ios/Podfile.lock
lib/src/chatlist/chat_list.dart
pubspec.lock
pubspec.yaml

[Original Issue](https://github.com/open-xchange/ox-coi/issues/271).
* adds a new Flutter plugin called [Slideable](https://pub.dev/packages/flutter_slidable)
* implements swipe to left function to delete a chat

OT-426: Swipe to delete in the chat list

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/exportOptions.plist
tools/build.iosDevReleaseBuild.sh

Create a build script for iOS
Created a shell script to automate the build and generate an ipa file

OT-508 Create build script for iOS

---

ios/Podfile.lock
lib/src/adaptiveWidgets/adaptive_icon.dart

https://jira.open-xchange.com/browse/OT-519
#277 
Changed material icons to cupertino icons.

OT-519 #277 Extend cupertino icon support

---

lib/src/chatlist/chat_list.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_list.dart

[Original Issue](https://github.com/open-xchange/ox-coi/issues/276).
* implements swipe to left function to delete a contact in contact list
* implements swipe to right function to block a contact in contact list
* implements swipe to right function to unblock a contact in blocked contact list

OT-518: Swipe Actions in Contact List

---

ios/Flutter/Release.xcconfig
ios/Flutter/development.xcconfig
ios/Flutter/stable.xcconfig
ios/OX Coi/Info.plist
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/development.xcscheme
ios/Runner.xcodeproj/xcshareddata/xcschemes/stable.xcscheme
ios/exportOptions.plist
tools/build.iosDevReleaseBuild.sh

#263 
https://jira.open-xchange.com/browse/OT-307
Name of App changed
Schemes are missing in XCode Projekt for matching Android flavors
Changed the name of the App
Added schemes to XCode Projekt

OT-307 #263 Renamed App and added schemes to xcode project

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/openxchange/oxcoi/MainActivity.java
assets/json/providers.json
lib/src/chatlist/chat_list.dart
lib/src/data/invite_service_resource.dart
lib/src/invite/invite_bloc.dart
lib/src/invite/invite_event_state.dart
lib/src/invite/invite_service.dart
lib/src/l10n/l.dart
lib/src/login/login_bloc.dart
lib/src/login/providers.dart
lib/src/main/root.dart
lib/src/platform/preferences.dart
lib/src/push/push_bloc.dart
lib/src/push/push_service.dart
lib/src/share/share_bloc.dart
lib/src/share/share_event_state.dart
lib/src/share/shared_data.dart
lib/src/user/user_profile.dart
lib/src/utils/constants.dart
lib/src/utils/http.dart
lib/src/utils/image.dart
lib/src/utils/text.dart
pubspec.lock

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-297)
For the user it should be possible to create an invite link and share it with his friends. When the friend has the app and taps on the link the app should be shown in the app chooser. Then the app should handle the link and give the user oppertunities tostart a chat or cancel the process.
Added the http class to provide http methods.

OT-297 Send and receive invite links OT-298 OT-299 OT-300 OT-301

---

lib/src/chatlist/chat_list_bloc.dart
lib/src/chatlist/invite_item.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart

Error UI on new invite
Error UI on automatic invite to chat conversion (for known contacts)
Multiple "encryption state changed messages" in the message list
Attachment handling triggered on tap on text message
Copy text from message not working
Naming in lib/src/message/message_item_bloc.dart
Fixed the "copy text" issue and discovered all those other small issues. No tickets exists.

HOTFIX multiple issues in the chat and message list

---

ios/Method.swift
ios/OX Coi/Application/AppDelegate.swift
ios/OX Coi/Info.plist
ios/OX Coi/Runner.entitlements
ios/Runner.xcodeproj/project.pbxproj
lib/src/utils/constants.dart

https://jira.open-xchange.com/browse/OT-300
Added deeplinks and custom url scheme to open the app from a link and route the invites directly to a chat

OT-300 Register deeplinks and custom scheme

---

lib/src/chat/chat.dart

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-404)
App is in background with open chat. If a message arrived it is was  marked as seen.
Just mark as seen when app is in foreground

OT-404 Read receipt is sent without reading the message

---

lib/src/user/user_profile.dart

#311 
https://jira.open-xchange.com/browse/OT-553
Added a Padding widget between buttons

OT-553 #311 Overlapping buttons in Profile

---

test_driver/setup/helper_methods.dart
test_driver/swipe_block_unblock_test.dart

Add test: Add swipe to block / unblock for contacts test.

OT-546 Add swipe to block / unblock for contacts test.

---

lib/src/adaptiveWidgets/adaptive_icon.dart
lib/src/chatlist/chat_list_item.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/contact_item_selectable.dart
lib/src/ui/dimensions.dart
lib/src/widgets/avatar_list_item.dart

https://github.com/open-xchange/ox-coi/issues/323
The check mark for added group participants on the "create group screen" was lost
Added the check mark.
Added the new UI for the check mark

Issue-323 Missing check mark during group creation

---

lib/src/contact/contact_change_bloc.dart
lib/src/contact/contact_change_event_state.dart
lib/src/contact/contact_list.dart

https://github.com/open-xchange/ox-coi/issues/325
There was no error message after deleting a contact with swipe.
Added an "await for" to wait for the success or failed callback and show a toast message.

Issue-325 Broken chat after swipe to delete in contact list

---

lib/src/l10n/l.dart
lib/src/settings/settings_security.dart

https://jira.open-xchange.com/browse/OT-583
Wrong usage of our translation helper.

OT-583 [code, null] copied to clipboard

---

lib/src/chat/chat.dart
lib/src/utils/text.dart

https://jira.open-xchange.com/browse/OT-577
Malformed phone numbers were handed over to the system, so it couldn't handle them.
Removing everything bit '+' and numbers.

OT-577 Unable to call contact

---

lib/src/chat/chat_create.dart
lib/src/chat/chat_create_group_settings.dart

#355 
Wrong list paddings during chat creation.
- Removed unnecessary padding
- Adjusted dividers size

Wrong list paddings

---

lib/main.dart

#353 
Wrong switch color.
Set the toggleableActiveColor.

Wrong switch color #353

---

lib/src/message/message_builder.dart

https://jira.open-xchange.com/browse/OT-447
Gifs are shown as generic file.
Gifs are shown as a gif when they are from type gif.

OT-447 Gifs are displayed as normal files (preview missing)

---

lib/src/contact/contact_change.dart
lib/src/contact/contact_change_bloc.dart
lib/src/contact/contact_change_event_state.dart
lib/src/contact/contact_import_bloc.dart
lib/src/contact/contact_import_event_state.dart
lib/src/contact/contact_list.dart
lib/src/l10n/l.dart
lib/src/navigation/navigatable.dart
lib/src/utils/constants.dart
lib/src/utils/dialog_builder.dart

https://github.com/open-xchange/ox-coi/issues/347
When a user starts a chat with a googlemail user and the user replies than a new chat/contact is created with a gmail account.
There is a check before adding a contact. When there is a googlemail email than the user is asked if he wants to change the email to gmail or not.
Added the onWillPop function parameter for showConfirmationDialog.

Two chats for one contact #347

---

lib/src/main/main_bloc.dart

https://jira.open-xchange.com/browse/OT-639
#368 
Contact list broken
The contacts table will be created on start if it not exists

Contact list is broken after import #368

---

lib/src/chat/chat_create.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_item.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/ui/dimensions.dart
lib/src/widgets/avatar_list_item.dart
pubspec.yaml

https://github.com/open-xchange/ox-coi/issues/366
The chatlist/contactlist flickers after deleting/blocking a chat/contact
Added the Listview.custom widget to just repaint the items when needed.

Flickering on swipe to delete / block #366

---

lib/src/chat/chat_create_group_settings.dart
lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/contact/contact_details.dart
lib/src/user/user_profile.dart
lib/src/widgets/profile_header.dart

https://github.com/open-xchange/ox-coi/issues/382
There were several problems with the new ProfileHeader.
Fixed the problems and added the new ProfileHeader in the chat profile screen, contact details screen and create group screen.

Profile view UI problems #382

---

tools/build.triggerBuild.sh
tools/test.runIntegrationTests.sh
tools/test.runSingleIntegrationTest.sh

#389 
- Executable from any folder
- Help added

Optimize build script #389

---

lib/main.dart
lib/src/background_refresh/background_refresh_manager.dart
lib/src/chat/chat.dart
lib/src/chat/chat_create_mixin.dart
lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_group_contact_item.dart
lib/src/chat/chat_profile_single.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_details.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_item_bloc.dart
lib/src/main/main_bloc.dart
lib/src/navigation/navigatable.dart
lib/src/navigation/navigation.dart
lib/src/notifications/local_notification_manager.dart
lib/src/notifications/notification_manager.dart
lib/src/qr/scan_qr.dart
lib/src/share/share.dart
lib/src/utils/text.dart
lib/src/widgets/avatar_list_item.dart
lib/src/widgets/list_group_header.dart

https://jira.open-xchange.com/browse/OT-674
We now get in app notifications for invites.
Now also listening to Event.msgsChanged which allows us to trigger notifications also for invites.
- **Please do not squash this**
- Fix empty contact item if name is empty
- Fix navigation stack handling and clean up
- Remove invites from sharing view
- Disallow tapping on group headers

Ot 674 no notification for invites

---

lib/src/chat/chat.dart
lib/src/chat/chat_change_bloc.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_import_bloc.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/contact_list_bloc.dart
lib/src/debug/debug_viewer.dart
lib/src/invite/invite_bloc.dart
lib/src/invite/invite_service.dart
lib/src/l10n/l.dart
lib/src/l10n/l10n.dart
lib/src/login/login_bloc.dart
lib/src/notifications/notification_manager.dart
lib/src/push/push_manager.dart
lib/src/push/push_service.dart
lib/src/qr/scan_qr.dart
lib/src/settings/settings_security.dart
lib/src/user/user_settings.dart
lib/src/widgets/avatar.dart
lib/src/widgets/placeholder_text.dart
lib/src/widgets/profile_body.dart
lib/src/widgets/state_info.dart
lib/src/widgets/validatable_text_form_field.dart
test/utils/date.dart
test/utils/text.dart

https://jira.open-xchange.com/browse/OT-515
Added a function to split text. 
Initially this simple splits by white space and eliminates occurrences of multiple white spaces before.
- Replaced all helper methods by method extensions
- Added some test for the new methods
- Added an extension method to check if a string contains a protocol, e.g. http://

OT-515 Split message content

---

lib/src/contact/contact_change.dart
lib/src/contact/contact_change_bloc.dart
lib/src/contact/contact_details.dart
lib/src/l10n/l.dart
lib/src/utils/error.dart

https://jira.open-xchange.com/browse/OT-687
We did not handle that case.
Now checking if a mail address is already used.

OT-678 Add Contact with same email shows Success message

---

lib/src/chat/chat_create_group_settings.dart
lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_details.dart
lib/src/contact/contact_item.dart
lib/src/share/share.dart
lib/src/user/user_profile.dart
lib/src/utils/text.dart
lib/src/widgets/profile_header.dart
test/utils/date.dart

https://jira.open-xchange.com/browse/OT-686
Added the on tap action for mails in all profile views.
Added the icon and tap action via ProfileHeader Widget.
- Fixed group headers for sharing, create group, blocked view (still missing is the **group profile view** which will be tackled in a separate ticket)
- Added padding in the sharing view
- Added padding for phone numbers in the edit contact view
- Fixed missing padding if no name is set in profile views
- Renaming, clean ups and using method extensions

OT-686 Copy mail address button function does not work

---

lib/src/chat/chat.dart
lib/src/flagged/flagged.dart
lib/src/flagged/flagged_bloc.dart
lib/src/flagged/flagged_events_state.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart

OT-540: List flagged messages per conversation

---

lib/src/chat/chat.dart

https://jira.open-xchange.com/browse/OT-691
User could send "empty" messages (white space, new lines etc.)
Added some checking to avoid this.

OT-691 Dissallow empty messages

---

lib/src/contact/contact_change_bloc.dart

#427 
We didn't handle the deletion of contacts with empty chats.
Added logic for the case *contact deletion success* &&  *chat exists* 
- Made renameChat method private

Deletion of contacts lead to empty chats #427

---

lib/src/chat/chat_profile_single.dart

Fixes #431 
Re-implements a confirmation dialog when a chat should be deleted.

OT-704: Fixes Missing Dialog When a Chat is Deleted

---

lib/src/contact/contact_import_bloc.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/contact_extension.dart
lib/src/invite/invite_bloc.dart
lib/src/main/main_bloc.dart
lib/src/utils/constants.dart
pubspec.lock

#432 
We now use our own file for the extension database.
- Made some stuff private
- Shorter method names
- More finals

Use separate database for extensions #432

---

lib/src/main/root.dart

#456 
The search bar got stuck after pressing back.
Added additional reset logic.

Search bar state not reset if back button is used #456

---

lib/src/chat/chat_profile_single.dart

#460 
Wrong wording.
Fixed the wording.

Wrong text for blocking in chat profile view #460

---

lib/src/l10n/l.dart
lib/src/navigation/navigation.dart
lib/src/settings/settings.dart
lib/src/settings/settings_encryption.dart
lib/src/settings/settings_encryption_bloc.dart
lib/src/settings/settings_encryption_event_state.dart
lib/src/user/user_profile.dart

Fixes #469 - Encryption-Settings Title
* Changes all related classes, types, methods, file names etc. too, to be consistent.

OT-740: Encryption-Settings Title

---

lib/src/l10n/l.dart
lib/src/user/user_profile.dart

OT-739: Rename "Profile" to "Profile and Settings"

---

lib/src/contact/contact_import_bloc.dart
lib/src/data/contact_extension.dart
pubspec.lock
pubspec.yaml

Fixes #465 - Move contact extension db and avatars
* Updates `sqflite` package from version 1.2.0 to version 1.3.0
Please check, if this works on Android as well.

fixes exposing 'extension.db' and avatar images

---

lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event_state.dart
lib/src/chatlist/chat_list_item.dart
lib/src/error/error_logger.dart
lib/src/log/log_manager.dart

https://jira.open-xchange.com/browse/OT-761
https://jira.open-xchange.com/browse/OT-763
Missing error handling in the chat list.
Added the error handling.
Fixed a general error handling problem in the async context.

OT-671 + OT-673 Chat list problems

---

lib/main.dart
lib/src/log/log_manager.dart
lib/src/platform/files.dart
lib/src/platform/system_information.dart
lib/src/settings/settings_encryption.dart
lib/src/settings/settings_encryption_bloc.dart
pubspec.yaml

#494 
Added missing parts for file logging and enabled it.
All information logged via our loggers are also logged into the file. Also enabled the logger to received log information from external sources e.g. the DCC.
- Added synchronized package (for guarded access to async methods)
- Updated device_info package and related calls

Enable file logging #494

---

lib/src/main/main_bloc.dart

#497 
COI settings were only enabled on first login.
Enabling COI related settings always if disabled but COI is enabled.
- Clean up for better readability

Enable COI filtering if COI is enabled but filtering not #497

---

lib/src/chat/chat.dart
pubspec.lock
pubspec.yaml

Fixes #476 - Unable to play received videos
* updates `file_picker` plugin to latest version
* implements a dirty hack, so that the Core can handle video as expected

OT-745: Unable To Play Received Videos

---

lib/src/platform/system_information.dart

No issue given.
Logging information for iOS system version weren't helpful.
Changed the data to be logged.
Changed the line endings of setup.developmentWithoutCore.sh to "linux".

Adjust iOS logging and fix setup.developmentWithoutCore.sh (wrong line endings)

---

lib/src/l10n/l.dart
lib/src/qr/show_qr.dart

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-778)
The qr code was not shown. The string was to long and the version for the qr code was to low.
Raised the qr code version from 6 to 8.
- Added a text widget to show the error of the qr widget to the user. 
- Added the error to the logger
- Made some variables final

OT-778 QR Code is not shown

---

lib/main.dart
lib/src/log/log_manager.dart
lib/src/notifications/local_notification_manager.dart

#509
Missing contact in the repository.
Adding contact to the repository if missing.
Delayed app start, to allow logger to setup completely.

Contact missing for invites. #509

---

lib/src/chat/chat_add_group_participants.dart
lib/src/chat/chat_create.dart
lib/src/chat/chat_create_group_participants.dart
lib/src/chatlist/chat_list.dart
lib/src/contact/contact_list.dart
lib/src/widgets/button.dart
lib/src/widgets/dynamic_appbar.dart

#478 
https://jira.open-xchange.com/browse/OT-749
Show text delete icon only when text has been entered
UI changes

Ot 749 show text delete icon only when text has been entered

---

lib/src/chat/chat_profile_group.dart
lib/src/l10n/l.dart

OT-675
Group leave is sometimes broken.
Adjusted the leave logic.

OT-675 Group leave broken

---

lib/src/data/config.dart
lib/src/login/login_bloc.dart
lib/src/login/password_changed_bloc.dart
lib/src/main/main_bloc.dart

Added missing load config call.

HOTFIX config broken

---

ios/Runner.xcodeproj/xcshareddata/xcschemes/development.xcscheme

HOTFIX: fixes typo 'OS COI...' in Xcode scheme

---

lib/src/data/config.dart
lib/src/login/login_bloc.dart
lib/src/login/password_changed_bloc.dart
lib/src/main/main_bloc.dart

None
The caching of config values makes no sense. It introduces more errors than it helps.
Remove the caching completely.

HOTFIX remove last update logic in config.dart

---

lib/src/log/log_manager.dart

None
It was possible that a log file couldn't get deleted, which lead to an exception
Fixed the broken guarding of that code part.

HOTFIX fixes log file deletion error message

---

assets/json/providers.json
lib/src/data/config.dart
lib/src/l10n/l.dart
lib/src/login/login_bloc.dart
lib/src/login/login_events_state.dart
lib/src/settings/settings_manual_form.dart
lib/src/settings/settings_manual_form_event_state.dart
lib/src/user/user_change_bloc.dart
lib/src/user/user_change_event_state.dart
lib/src/utils/core.dart

https://github.com/open-xchange/ox-coi/issues/549
The core has new parameters for the config (login).
Added the new arguments and changed the code to handle them.
**Additional information**
Changed the providers.json to handle the new flow.

Adjust client login flow to new core handling #549

---

lib/src/l10n/l.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart
lib/src/navigation/navigatable.dart

https://github.com/open-xchange/ox-coi/issues/529
Due to numerous reasons (server config, network problems, client problems) it's possible that a message couldn't get sent. This is most of the time visible in the UI as hourglass or error icon right beside the actual message. But the state is not reliable.
If one message is erroneous the whole sending of messages can get stuck also.
Added a dialog to tell the user that there are errors and when the message is not deleted the sending of new messages can get stuck. The dialog has the options "Cancel" and "Delete message".

File sending failed and stuck messages on sending #529

---

lib/src/gallery/gallery_bloc.dart
lib/src/message/message_attachment_bloc.dart
pubspec.lock
pubspec.yaml

#521 
- Missing thumbnails
- VideoPlayer broken on iOS
- Now saving thumbnails on Dart level
- Using .network call for VideoPlayer to fix iOS problems
- Cleanup

Preview image for specific file types missing OT-795 #521

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event_state.dart
lib/src/gallery/gallery.dart

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-729)
- Missing view updates
- Missing data on invites opened from pushes
- Adjusted listener registration
- Adjusted general flows
- Added missing message on invites opened from push
- Created separate widgets as first stop to a "cleaned up chart.dart" file

OT-729 Chat sometimes does not refresh automatically

---

lib/src/message/message_item_bloc.dart
lib/src/user/user_bloc.dart
lib/src/user/user_change_bloc.dart
lib/src/user/user_change_event_state.dart
lib/src/user/user_event_state.dart
lib/src/user/user_profile.dart
lib/src/user/user_settings.dart

The username was not changed in the user profile after saving the new name. After restart or changing the view it was updated.
The config is requested again after saving the new user data. 
- The `UserChangeBloc` has an optional UserBloc now
- Some clean up in all changed files

HOTFIX Username was not updated after change

---

lib/src/dynamic_screen/widgets/screen_components/dynamic_screen_app_bar.dart
lib/src/dynamic_screen/widgets/screen_components/dynamic_screen_navigation.dart
lib/src/utils/keyMapping.dart

None
Added keys for the onboarding.

Add keys to make onboarding testable

---

tools/build.triggerBuild.sh
tools/setup.loadCustomer.sh

None
Added a check to verify the required customer repository is given.

BUILD Add customer check to build script

---

lib/src/widgets/profile_header.dart

Fixes https://github.com/open-xchange/ox-coi/issues/569
If the avatar is empty and the user wants to add an image the BottomSheet shows the option "Remove actual image".
Removed the option if the avatar path is empty.

Button should be disabled until action makes sense #569

---

.gitignore
test_driver/account_settings_test.dart
test_driver/block_unblock_test.dart
test_driver/chat_list_test.dart
test_driver/contact_list_test.dart
test_driver/flagged_test.dart
test_driver/group_test.dart
test_driver/login_test.dart
test_driver/messages_actions_test.dart
test_driver/profile_test.dart
test_driver/setup/helper_methods.dart
test_driver/setup/main_test_setup.dart
test_driver/setup/test_config_credential.dart
test_driver/setup/test_constants.dart
tools/test.runIntegrationTests.sh
tools/test.runSingleIntegrationTest.sh

#543 
**Problem**
Flagged test remains unstable,
The problem could always be the length of the message.

Make test backend configurable #543

---

lib/generated/l_dynamic.dart
lib/src/l10n/l.dart
translations/oxcoi.pot

HOTFIX update translations

---

lib/main.dart
lib/src/customer/customer.dart
lib/src/customer/customer_delegate.dart
lib/src/data/config.dart
lib/src/data/config_extension.dart
lib/src/extensions/numbers_apis.dart
lib/src/main/main_bloc.dart
lib/src/main/main_event_state.dart
lib/src/notifications/notification_manager.dart
lib/src/push/push_manager.dart
lib/src/settings/settings_chat_bloc.dart
lib/src/settings/settings_notifications_bloc.dart

None
- Missing push registration during start
- Notification settings not loading
- Exceptions during entering a chat
- Wrongly started background service
1. Start app
2. COI is supported: Set config values for COI (on first start)
3. Onboarding done or disabled
4. COI is supported: Register push (on first start) and start push, COI is not supported: Start background handling
- Config now handles COI variables (previously located in the Customer area)
- Config hardened and cleaned up
- Removed the BuildContext requirement from the MainBloc
- Customer logic reduced to a minimum

HOTFIX repair broken setup for different cases

---

ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
test_driver/onboarding_test.dart
test_driver/profile_test.dart
test_driver/setup/main_test_setup.dart
test_driver/setup/test_constants.dart

#576
Please do not forget to get a look of to the key for the placeholder of the user profile in first onboarding view. Used of consistent key could be better.

Create onboarding test #576

---

android/app/build.gradle
ios/Flutter/Debug-development.xcconfig
ios/Flutter/Release-development.xcconfig
ios/Flutter/Release-stable.xcconfig
ios/OX Coi/cs-CZ.lproj/InfoPlist.strings
ios/OX Coi/da-DK.lproj/InfoPlist.strings
ios/OX Coi/de.lproj/InfoPlist.strings
ios/OX Coi/en-US.lproj/InfoPlist.strings
ios/OX Coi/en.lproj/InfoPlist.strings
ios/OX Coi/es-MX.lproj/InfoPlist.strings
ios/OX Coi/es.lproj/InfoPlist.strings
ios/OX Coi/fi-FI.lproj/InfoPlist.strings
ios/OX Coi/fr-CA.lproj/InfoPlist.strings
ios/OX Coi/hu-HU.lproj/InfoPlist.strings
ios/OX Coi/ja-JP.lproj/InfoPlist.strings
ios/OX Coi/lv-LV.lproj/InfoPlist.strings
ios/OX Coi/nl-NL.lproj/InfoPlist.strings
ios/OX Coi/pl-PL.lproj/InfoPlist.strings
ios/OX Coi/pt.lproj/InfoPlist.strings
ios/OX Coi/ro-RO.lproj/InfoPlist.strings
ios/OX Coi/ru-RU.lproj/InfoPlist.strings
ios/OX Coi/sk-SK.lproj/InfoPlist.strings
ios/OX Coi/sv-SE.lproj/InfoPlist.strings
ios/OX Coi/zh-Hant-CN.lproj/InfoPlist.strings
ios/OX Coi/zh-Hant-TW.lproj/InfoPlist.strings

OT-838 rename app

---

assets/customer/json/onboarding.json
lib/generated/l_dynamic.dart
lib/src/contact/contact_list_bloc.dart
lib/src/contact/contact_list_event_state.dart
lib/src/customer/customer_delegate.dart
lib/src/l10n/l.dart
tools/gendl/gendl.dart

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-500)
Import was missing during onboarding.
- Added the UI to the JSON file
- Added the required callbacks
- Adjusted the BloC to allow "ui-less" contact import
- Fixed typo in generation tool
- Fixed generated class

HOTFIX add contact import to onboarding

---

lib/src/customer/customer.dart
lib/src/l10n/l10n.dart
lib/src/login/login_bloc.dart
lib/src/utils/assets.dart
lib/src/web/web_asset_bloc.dart
test_driver/onboarding_test.dart
test_driver/setup/main_test_setup.dart

Tests were not working, due to `rootBundle.loadString` bug https://github.com/flutter/flutter/issues/44182
- Added helper to avoid the error prone method
- Fixed onboarding test

HOTFIX repair tests

---

test_driver/login_test.dart
test_driver/onboarding_test.dart
test_driver/setup/helper_methods.dart
test_driver/setup/main_test_setup.dart

#586 
Document testing helper / setup methods

Document testing helper / setup methods  #586
