lib/source/data/config.dart
lib/source/profile/edit_user_settings.dart
lib/source/profile/profile.dart
lib/source/profile/user_bloc.dart
lib/source/utils/widget.dart

- Allowing null values for config values if a specific type is given
- Added image_picker and image_cropper
- Added a UI to choose between camera, gallery and resetting of the set avatar image
- Cleanups and smaller adjustments
I used async requests in a Flutter widget. This is intentional and I will adjust the documentation accordingly. We should never load data from the DCC via async events in Flutter widgets, but if a call to a plugin or something similar is made, which ONLY affects UI states, it's okay to use those calls. More or less the same logic applies as for the calling of setState.

OT-102 #5 Re-enable avatar selection in profile view

---

lib/src/contact/contact_change.dart
lib/src/contact/contact_list_bloc.dart
lib/src/l10n/localizations.dart

#12 
The contacts aren't correctly sorted and are broken after an update (e.g. change a name).
- Our getAllIds logic after an update was simply wrong, we need to get the list directly from the DCC
- We just need to iterate over the valid contacts instead of the complex solution (which also breaks the sorting done by the DCC) we applied before
- Also fixed some translations issues
- Also fixed a jumpy cursor in the ChangeContact view
None

OT-120 Broken contact list after contact edit #12

---

lib/main.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_invite_item.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/data/config.dart
lib/src/login/login.dart
lib/src/login/login_bloc.dart
lib/src/login/login_events.dart
lib/src/navigation/navigation.dart
lib/src/profile/edit_account_settings.dart
lib/src/profile/edit_user_settings.dart
lib/src/profile/profile.dart
lib/src/profile/user_bloc.dart
lib/src/profile/user_event.dart
lib/src/utils/protocol_security_converter.dart
lib/src/widgets/dialog_builder.dart

---
name: Pull request
about: Create a pull request to improve or extend the code
title: ''
labels: ''
assignees: ''
---
https://github.com/open-xchange/ox-talk/issues/9
The IMAP and SMTP security options were not saved.
Now it is possible to save the protocol security options. I've  added a new utils class which handles the generation of the server flags and everything which is needed for the protocol security options.
I also added a new parameter for the navigation methods to see which class is called.

OT-92 #9 IMAP and SMTP security setting is not used

---

lib/main.dart
lib/src/base/base_root_child.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list_view.dart
lib/src/contact/contact_import_bloc.dart
lib/src/data/config.dart
lib/src/l10n/localizations.dart
lib/src/main/main_bloc.dart
lib/src/main/root.dart
lib/src/platform/app_information.dart
lib/src/platform/preferences.dart
lib/src/profile/profile.dart
lib/src/utils/colors.dart
lib/src/utils/dimensions.dart
lib/src/widgets/avatar.dart
pubspec.yaml

https://github.com/open-xchange/ox-talk/issues/27
All incoming mails were collected in the invites view. Only messages by other chat clients should be added to the invites view.
Used the updated DCC to filter the incoming mails.
- Added the accent color
- Adjusted the tab bar color in the chat list 
- Added an indicator for new invites
- Added better handling for shared preferences
- Added to ability to receive app information via the package_info plugin (version, build numbers and so on)
- Optimized the initial setup of the app (default values are now applied reliable at the first app start)
- Optimized loading performance of avatar list items

 OT-126 Show only chat invites #27 

---

lib/src/l10n/localizations.dart
lib/src/login/login.dart
lib/src/login/login_bloc.dart
lib/src/utils/dialog_builder.dart
lib/src/utils/error.dart

#6 
No user visible feedback on login errors.
Now listening to error events emitted by the DCC. If an error occurs show it as dialog, but only if the login failed (not during the process, as multiple errors can occur while auto configuring).

OT-116 Add error handling for the login process #6

---

lib/src/data/config.dart
lib/src/data/repository.dart
lib/src/data/repository_stream_handler.dart
lib/src/l10n/localizations.dart
lib/src/login/login_bloc.dart
lib/src/platform/system.dart
lib/src/profile/edit_account_settings.dart
lib/src/profile/user_bloc.dart

#29 
Context.configure() wasn't called.
Added the configure logic and error handling.
- Simplified the config logic
- Removed wrong "tearDown" and "close" methods for streams
- Added system.dart as helper class for system calls

OT-129 Edit account settings are not applied #29

---

lib/src/contact/contact_change_bloc.dart

#37 
- The chat name is now directly set on contact name change
- The chat name is now directly set instead of resetting it and waiting for the next request to the DCC to get the data

OT-143 Chat title is not updated after contact name change #37

---

lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event.dart
lib/src/chat/chat_profile_group_contact_item.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_single_view.dart
lib/src/chat/chat_profile_view.dart
lib/src/chat/chat_state.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_item_builder_mixin.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/contact_repository.dart
lib/src/l10n/localizations.dart
lib/src/utils/styles.dart

https://github.com/open-xchange/ox-talk/issues/36
The user can tap on the avatar/name section in the chat AppBar to see the ChatProfileView. This view has an avatar and the username & email (or in a group just the group name). In a single chat the user can tap on the email to copy it to the clipboard and he can block the user. In a Group Chat we have a list of all members of the group,.
The ChatProfileView loads the chat and differentiates between single and group chats. Then the ChatProfileSingleView/ChatProfileGroupView is called and build the expected view.
The function to tap the email in the single chat to copy it to clipboard and list all members …

Create chat profile view #36 OT-142

---

lib/src/chat/change_chat_bloc.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_view.dart

https://github.com/open-xchange/ox-talk/issues/44
The invites are not removed when a Chat was created with a contact from the invites.
The MessageRepository for the invites is cleared after creating a chat.  We do the same by creating a Chat from an invite.
Removed some unused Imports.

fixed Invites are not removed if a new chat is created #44 OT-149

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event.dart
lib/src/chat/chat_state.dart
lib/src/chatlist/chat_list_item.dart
lib/src/widgets/avatar_list_item.dart

https://github.com/open-xchange/ox-talk/issues/54
There was no indicator for new messages in the ChatList.
I added an indicator in the AvatarListItem to show how many new messages are in a chat.
A chat is marked as noticed when it is opened. This clears the indicator in the ChatList.

Add new message counter for chats #54

---

lib/src/chat/chat.dart
lib/src/chat/chat_composer_bloc.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_view.dart
lib/src/chat/create_chat.dart
lib/src/chat/create_group_chat.dart
lib/src/chatlist/chat_list_bloc.dart
lib/src/contact/contact_blocked_list.dart
lib/src/contact/contact_list.dart
lib/src/contact/contact_list_bloc.dart
lib/src/data/contact_repository.dart
lib/src/data/contact_repository_updater.dart
lib/src/message/message_item_bloc.dart
lib/src/widgets/avatar_list_item.dart

#66 
Contacts from invites where shown in the normal contact list.
Fixed the wrong displaying by separating the valid and invite contacts into different repositories. See https://github.com/open-xchange/ox-talk/compare/issue-66?expand=1#diff-5fe772f9d2183d2cff78acbbc5513f0c for the actual fix
- Removed duplicated constants for message types
- Simplified https://github.com/open-xchange/ox-talk/compare/issue-66?expand=1#diff-b7fd1bfde16ac22624f1b064bba32cbc by removing the different events and adding the contact type to the default request event. Also cleaned up the file
- Created https://github.com/open-xchange/ox-talk/compare/issue-66?expand=1#diff-368c7 …

Contacts from invites are shown in the contact list #66 OT-166

---

lib/src/base/base_root_child.dart
lib/src/chat/change_chat_bloc.dart
lib/src/chat/change_chat_event.dart
lib/src/chat/chat_profile_group_view.dart
lib/src/chat/chat_profile_single_view.dart
lib/src/chatlist/chat_list.dart
lib/src/chatlist/chat_list_item.dart
lib/src/chatlist/chat_list_view.dart
lib/src/contact/contact_list.dart
lib/src/l10n/localizations.dart
lib/src/maillist/mail_list.dart
lib/src/main/root.dart
lib/src/profile/profile.dart
lib/src/utils/dialog_builder.dart

https://github.com/open-xchange/ox-talk/issues/63
It was not possible to delete a chat.
Added buttons to the ChatProfileViews to delete a chat or leave a group.
Implemented the MultiSelect in the ChatList to delete more than one chat, but the long press action is removed because of a bug.

Delete chats #63

---

lib/src/chat/chat.dart
lib/src/chat/chat_create_group_settings.dart
lib/src/contact/contact_change.dart
lib/src/l10n/localizations.dart
lib/src/login/login.dart
lib/src/message/message_action.dart
lib/src/message/message_builder_mixin.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_state.dart
lib/src/message/message_received_view.dart
lib/src/message/message_sent_view.dart
lib/src/message/message_special_view.dart
lib/src/navigation/navigatable.dart
lib/src/settings/settings_autocrypt_bloc.dart
lib/src/settings/settings_autocrypt_event.dart
lib/src/settings/settings_autocrypt_import.dart
lib/src/settings/settings_autocrypt_state.dart
lib/src/settings/settings_security.dart
lib/src/settings/settings_security_bloc.dart
lib/src/settings/settings_security_state.dart
lib/src/share/share.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/utils/colors.dart
lib/src/utils/text.dart
lib/src/utils/widgets.dart
lib/src/widgets/avatar_list_item.dart
lib/src/widgets/placeholder_text.dart
lib/src/widgets/validatable_text_form_field.dart

#100 
Added support for creating a setup message (via the settings) and import the created message (clicking on the message within the chat view).
- Moved identical methods to util classes
- Rewrote our message_item to be better reusable
- Rewrote the validatable_text_form_field to be better reusable
- Optimized the dialog usage
- Optimized our avatar_item to be better reusable
Actual changes are mostly located in the settings_* area.

Support Autocrypt Setup Message #100 OT-206

---

lib/src/l10n/localizations.dart
lib/src/settings/settings_chat.dart
lib/src/settings/settings_chat_bloc.dart
lib/src/settings/settings_chat_event_state.dart

https://github.com/open-xchange/ox-coi/issues/122
It was not possible to change the config to get invites from all emails, accepted contacts or only chats.
Added another settings option in the ChatSettingsScreen to select an Option from a DropDown Menu.

Provide setting to handle all messages #122 OT-223

---

lib/src/settings/settings_security.dart

#136 
The setup code was null and the isNotEmpty call lead to an exception. Fixed that by also checking for null.

Add visusal feedback if key import was successfully #136

---

lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_list.dart
lib/src/login/login_provider_signin.dart
lib/src/widgets/validatable_text_form_field.dart

https://github.com/open-xchange/ox-coi/issues/138
- After adding a dot in the SMTP or IMAP server field, a space is added
- Sometimes entered text is exchange, e.g. "smtp" is tranferred to "SMTP"
- Upper and lowercase is sometimes guessed
Disabled autocorrect for the ValidatableTextFormField. And set the inputType for the server adresses to TextInputType.url
Fixed wrong or missing navigation.current

Disable text suggestions in server setup fields #138

---

android/app/build.gradle

We have to enforce 32 bit for now, even for debug builds, otherwise the CI builds will fail on some devices.

OT-258 build 32 bit also for debug

---

lib/src/contact/contact_change.dart
lib/src/l10n/localizations.dart
lib/src/qr/qr.dart
lib/src/user/user_profile.dart

https://github.com/open-xchange/ox-coi/issues/142
No button to scan a qr code in the add contact view.
Added missing button and pressing the button navigates to the qr.dart with scan-qr-tab selected.

Add QR option to "Add Contact" function #142 OT-248

---

lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_list_bloc.dart

#28
- We are already doing paged loading, as we only load messages relevant for the view port. The flickering after receiving or sending a message is based on a Flutter framework bug (see https://github.com/flutter/flutter/issues/21023), as all elements which change their index are recreated, even if matching objects (for given identical keys) could be used. We have to wait until the framework bug is fixed
- Removing the reverse logic would lead to huge problems when scrolling the view (on start, on new message, on compose and so on). Doing this manually would be problematic and error prone
**Changes:**
- Removed the loading spinner for messages
- Removed the loading state for messages
- Tried to …

OT-128 Enhance chat message view #28

---

lib/src/login/login.dart
lib/src/login/login_provider_list.dart

https://jira.open-xchange.com/browse/OT-333
- Added a check to get the current context and only show the other provider button if the login context is active
- Also centered the welcome text
- Added a white space in the bottom text

OT-333 Register: do not show Other mail provider option

---

lib/src/l10n/l.dart
lib/src/settings/settings_notifications.dart
lib/src/settings/settings_notifications_bloc.dart
lib/src/settings/settings_notifications_event_state.dart
pubspec.yaml

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-421)
The "Enable background updates" option was displayed in the settings, even if we have a coi server.
Added another option when we have a coi-server that leads to the app settings.

OT-421 Hide "Enable background updates"

---

android/app/src/main/java/com/openxchange/oxcoi/MainActivity.java
lib/src/chat/chat.dart
lib/src/message/message_attachment_bloc.dart
lib/src/message/message_item.dart
pubspec.yaml

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-448)
Sharing a file from our app with our app ended in empty messages.
Removed the sharing library. The app handles the intent for sharing files itself.
The option to send files with text is not active but possible.

OT-448 Sharing a file to own app is not possible

---

.gitignore
ios/Podfile.lock

Since every `pod install` triggers an update of the `Podfile.lock` file we should put it to the Git ignore list.

HOTFIX: adds Podfile.lock to .gitignore

---

lib/src/chat/chat.dart

On devices with rounded corner displays there are so called safe areas. When composing a chat message, the bottom bar containing the text field should take note for this (bottom) safe area.

HOTFIX: adds support for bottom safe area

---

lib/src/chatlist/chat_list_bloc.dart
lib/src/login/login_bloc.dart
lib/src/notifications/local_push_manager.dart
lib/src/push/push_bloc.dart
lib/src/qr/qr_bloc.dart
lib/src/settings/settings_security_bloc.dart

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-454)
We had a general problem with updating the chat list order if the list wasn't open.
Now updating the values, instead of just adding them if missing. This reorders the list and fixes the problem.
- Added some guards for listener deregistration
- Please also see the related pull request in the plugin: https://github.com/open-xchange/flutter-deltachat-core/pull/52

OT-454 Autocrypt setup is not sorted correctly into chat list

---

lib/src/qr/qr_bloc.dart

#242
The user who started the verification didn't saw the verified icon of the other user until a restart of the app was performed.
The verified state of our cached contact entry is now reloaded after a successful verify. As this was missing the repository wasn't updated, so a restart was needed.
Also added a null check, even though the contactId shouldn't be ever null.

OT-490 #242 Verified icon not shown

---

lib/src/contact/contact_import_bloc.dart

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-414?src=confmacro)
Mobile-number is available after deleting and reimporting. The contact extension was not updated correctly.
Updated the contact extension correctly.

OT-414 Mobile-number is available after deleting and reimporting

---

lib/src/adaptiveWidgets/adaptive_app_bar.dart

#309 
The black text color is now white.
For now just changed the brightness mode. As a long term fix https://github.com/open-xchange/ox-coi/issues/258 will be used.
Removed unnecessary border.

iOS appbar title font is black

---

lib/src/adaptiveWidgets/adaptive_icon.dart
lib/src/chat/chat_profile_group_contact_item.dart
lib/src/l10n/l.dart
lib/src/message/message_action.dart
lib/src/message/message_builder.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart
lib/src/message/message_list_bloc.dart
lib/src/message/message_list_event_state.dart
lib/src/navigation/navigatable.dart
pubspec.lock

https://github.com/open-xchange/ox-coi/issues/255
There is no visual feedback to the user when the send of a message failed or the message is in pending mode.
Added new icons to visualize missing states and added different message actions.
- Localized hardcoded action Strings.
- Add iOS part in plugin before merge: https://github.com/open-xchange/flutter-deltachat-core/pull/67

Issue-255 Visualize send errors OT-502

---

ios/Runner.xcodeproj/project.pbxproj
pubspec.lock
pubspec.yaml

On iOS it is not possible to send audio messages.
The problem was an issue in a Flutter plugin we use. See [our pull request here](https://github.com/dooboolab/flutter_sound/pull/168).
This pull request just changes the reference to our own fork of that (fixed) plugin until the PR gets accepted and merged into the official version.
[internal bug tracker](https://jira.open-xchange.com/browse/OT-572)

OT-572: Not possible to send Audio Message

---

ios/OX Coi/Info.plist

https://jira.open-xchange.com/browse/OT-582
We want to expose exported app files to the iOS system (e.g. the Files app), so the user can use the exported / saved data.
We use path_provider with the getApplicationDocumentsDirectory() method which uses the `NSDocumentDirectory` API. This seems to be the right approach, but we also have to adjust our Info.plist to allow the system accessing the folder.
Information found here https://stackoverflow.com/questions/55220612/how-to-save-a-text-file-in-external-storage-in-ios-using-flutter

OT-582 Unaccessible path for key export/import

---

lib/src/background_refresh/background_refresh_manager.dart
lib/src/data/repository.dart
lib/src/data/repository_stream_handler.dart
lib/src/error/error_bloc.dart
lib/src/login/login_bloc.dart
lib/src/notifications/local_push_manager.dart
lib/src/push/push_bloc.dart
lib/src/qr/qr_bloc.dart
lib/src/settings/settings_security_bloc.dart
tools/test.runIntegrationTests.sh

#334
Added easier and more clear registration and deregistration of listeners for core events.
The actual logic change is in the plugin repository (https://github.com/open-xchange/flutter-deltachat-core/pull/68). This PR only adjusts the calls.
- Please also review / merge https://github.com/open-xchange/flutter-deltachat-core/pull/68
- lib/src/push/push_bloc.dart intentionally doesn't listen to Event.error anymore
- Updated the test script to check for exceptions

Events not handled correctly #334

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event_state.dart

https://github.com/open-xchange/ox-coi/issues/196
The notifications for a chat where not removed after entering the chat.
Added a call to ChatBloc to cancel the notifications for the specified chatId.

Push: remove notifications when entering a conversation manually #196

---

lib/src/chat/chat.dart

https://jira.open-xchange.com/browse/OT-574
Files app instead of photo app is used for GIF selection
Removed GIF selection, users can use Image / Video to add GIFs to conversations. The GIF entry will later return with proper integration of e.g. external GIF services.

OT-574 Files app instead of photo app is used for GIF selection

---

lib/src/contact/contact_change_bloc.dart

https://jira.open-xchange.com/browse/OT-598 (internal ticket only)
Contacts weren't visible after unblocking, if a contact wasn't added in before blocking.
Now checking if an unblocked contact is know and in the database, otherwise it's added now.
Requires https://github.com/open-xchange/flutter-deltachat-core/pull/73 to be merged.

OT-598 No Option to add an unblocked unknown user to contacts

---

lib/src/l10n/l.dart
lib/src/login/login_manual_settings.dart
lib/src/settings/settings_manual_form.dart
lib/src/settings/settings_manual_form_bloc.dart
lib/src/settings/settings_manual_form_event_state.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_change_bloc.dart
pubspec.lock

https://github.com/open-xchange/ox-coi/issues/346
The fields for IMAP/SMTP login names were missing in the account settings.
Added the missing fields to the account settings page.
Fixed a problem of small page jump in the account settings.

E-mail address and ISP login assumed to be the same #346

---

lib/src/background_refresh/background_refresh_manager.dart

#195 
Refreshing via background job wasn't reliable.
Threads weren't always ready, now starting them if needed. 
Numerous plugin updates and the Flutter framework update also helped a lot here.

Push Reliability #195

---

lib/src/contact/contact_change.dart
pubspec.lock
pubspec.yaml

#391
We called the method wrong.
We call the method the right way:
```
onTap: () => scanQr() // works
onTap: scanQr // works
onTap: () => scanQr // doesn't work
```
Fixed the dependency to the qr_mobile_vision lib (Android only). We are currently using our fork, as the actual library doesn't support the required Android v2 embedding. As soon the lib integrates v2 embedding we switch back.

Scan QR code doesn't work #391

---

lib/src/chat/chat.dart

#392
We used an InkWell Widget. This requires a top level Material Widget. This wasn't present at the time of creation of the initial widget tree. 
Replaced it with a GestureDetector, which doesn't require a Material Widget.
@florianhaar we often had the problem with GestureDetectors only recognizing tabs on the child Widgets, but not on the areas inbetween. I just found the Flutter documentation (https://api.flutter.dev/flutter/rendering/HitTestBehavior-class.html) for that problem and the fix is actually pretty simple (`HitTestBehavior.opaque` or similar depending on the wanted behavior).

Blinking Flutter-Error when entering a chat #392

---

assets/customer/customer_config.json
lib/src/customer/customer_config.dart
lib/src/login/login_provider_signin.dart
lib/src/main/main_bloc.dart
pubspec.yaml

https://github.com/open-xchange/ox-coi/issues/301
It should be possible to show pre-defined chats after login and after updates.
There is a customer_config.json with different informations (name, list of pre-defined chats,...). When the app is configured we load the customer_config and create the chats if needed.
The "deletable" field has no affect at the moment

Add pre-defined chat #301

---

lib/src/chatlist/chat_list.dart
lib/src/contact/contact_list.dart
lib/src/main/root_child.dart

https://github.com/open-xchange/ox-coi/issues/388
Opening flagged messages in the chat list and blocked contacts in the contact list is not needed anymore.
Removed the actions from the appbar.

Duplicated navigation paths #388

---

lib/src/widgets/validatable_text_form_field.dart

https://github.com/open-xchange/ox-coi/issues/397
Emails with space character at the end are not validated correct.
Emails are trimmed while validation and returned.

Emails are not trimmed #397

---

lib/src/contact/contact_list.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_signin.dart
lib/src/login/password_changed.dart
lib/src/main/root.dart
lib/src/navigation/navigation.dart
lib/src/qr/qr.dart
lib/src/qr/scan_qr.dart
lib/src/settings/settings_security.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/widgets/fullscreen_progress.dart

#405
Our progress overlay allowed tab, scroll and back actions during the progress.
Capturing and dismissing all tap events. Added "back check" where required. 
- Created a wrapper for the progress Widget (extends OverlayEntry) which automatically enables / disables back navigation
- Cleaned up the create / dismiss logic for overlays
- Global navigation state for back navigation added

Progress screen doesn't block taps #405

---

lib/src/push/push_service.dart
lib/src/user/user_profile.dart
lib/src/widgets/settings_item.dart
tools/build.triggerBuild.sh

#415 
We weren't able to build the app without a Rust tool chain.
Added the possibility to use pre-compiled DCC binaries in the build script. Those are provided by the flutter-deltachat-core plugin releases. A local build is still possible. Executing the script will also allow developers without Rust tool chain to develop the app. The given changes allow easier CI builds.
- Re-enabled the debug setting in the app
- Fixed a "null checking" bug during push registration
- @CihanOezkan we need to add a few lines to also support iOS with downloaded DCC binaries. Please just add another commit on this branch.

Extend build script to re-enable CI builds #415

---

lib/src/l10n/l.dart
lib/src/settings/settings_security.dart

https://github.com/open-xchange/ox-coi/issues/408
The wording for import/export was not really understandable for the user.
- New and different Strings for both platforms
- On Android we show a user readable path for export

Clarify wording after key export #408

---

lib/src/chat/chat.dart

https://jira.open-xchange.com/browse/OT-725
If the app needs a moment to load a huge image / attachment, it is possible to send empty message if the user is fast.
Only allowing non-empty text messages.

OT-725 When sending pictures I sometimes succeed in sending empty messages

---

lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/contact/contact_details.dart

Fixes #483, Closes #483 
* adds missing `chatId` parameter when calling `Flagged` widget
* comments some code out (needs to be discussed) for flagged messages per contact

OT-757: Regression: Flagged Messages not filtered per Chat

---

lib/src/l10n/l.dart
lib/src/message/message_builder.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart
lib/src/message/message_received.dart
lib/src/message/message_sent.dart

https://github.com/open-xchange/ox-coi/issues/337
It was not possible to see which messages where forwarded.
- Added the StatelessWidget MessagePartForwarded to the MessageBuilder
- Added translation key "Forwarded"
- Added the forwarded widget where needed
- This needs to be merged first https://github.com/open-xchange/flutter-deltachat-core/pull/77
- And the plugin iOS part needs to be implemented

Forward state for messages #337

---

lib/src/chat/chat.dart
lib/src/chat/chat_profile.dart
lib/src/chat/chat_profile_single.dart
lib/src/utils/keyMapping.dart
test_driver/flagged_test.dart
test_driver/messages_actions_test.dart
test_driver/setup/helper_methods.dart
test_driver/setup/test_constants.dart
tools/test.runIntegrationTests.sh

#439 
Add test for flagged messages per chat
**Workflow:**
1. Login
2. Add two chats
3. Edit two messages in the first chat, flags both and return to the chat view.
4. Edit one message in the second chat, flags that one, and navigate to the flagged view to check if all flagged messages are available, and back to the chat view.
5. Navigate to flag view though one chat, unflag all messages and back to the chat view.

Add test for flagged messages per chat #439

---

lib/src/l10n/l.dart

https://github.com/open-xchange/ox-coi/issues/491
Modified error string for the case that a contact is in a group and can't be deleted.

Empty user in group profile after deletion #491

---

lib/src/brandable/custom_theme.dart

https://jira.open-xchange.com/browse/OT-758
https://github.com/open-xchange/ox-coi/issues/486
The current contrast between Secondary and Accent color is too low
Changed colors for Secondary and Accent in dark mode

Ot 758 update secondary and accent color for dark mode

---

lib/src/message/message_builder.dart

https://jira.open-xchange.com/browse/OT-781
#502 
Bottom padding of "Forwarded" was not given
Added a bottom padding for "Forwarded" message

UI issues if forwarded message is shown #502

---

lib/src/data/config.dart
lib/src/main/main_bloc.dart
lib/src/utils/constants.dart

Now using the config value instead of the hard coded value. Initial value is 100MB.

Use max size config value

---

lib/src/chat/chat_profile_group.dart
lib/src/platform/preferences.dart
lib/src/user/user_profile.dart
lib/src/utils/keyMapping.dart
test_driver/account_settings_test.dart
test_driver/block_unblock_test.dart
test_driver/group_test.dart
test_driver/security_settings_test.dart
test_driver/setup/main_test_setup.dart

None
Tests were failing due to the new file logging, which introduced a delayed start of the whole app. Also the group leave / delete handling changed.
- Fixed some keys
- Added a check if the app is ready for the tests (not the best solution but it's working and a known problem https://github.com/flutter/flutter/issues/41029)
- Adjusted the group test to check for leave and delete (previously this was one step, now two).
- Remove two unused imports

HOTFIX repair tests

---

lib/src/contact/contact_change.dart
lib/src/login/login_provider_signin.dart
lib/src/login/password_changed.dart
lib/src/settings/settings_manual_form.dart
lib/src/widgets/validatable_text_form_field.dart

Fixes #531 
We manually added the icons to the UI, but our text fields should and could supply those.
- Let the text fields handle prefix and suffix icon
- Use the `icon` and the `suffixIcon` properties (icon shows the icon on the left in front of the actual field and not inside and that's what we want)
- I replaced our "specific icon on / off" logic with a more dynamic approach. We can now just set any icon we want, if one is required or just omit it
- Renamed TextFormType to TextType as it's shorter and clearer
- Added the person and lock icon on the password change screen (to match the normal login) 
- lib/src/settings/settings_manual_form.dart only …

Adding a new contact with empty fields lets slip the email icon #531

---

lib/src/chat/chat.dart
lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_details.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/l10n/l.dart
lib/src/login/login.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_signin.dart
lib/src/main/root.dart
lib/src/message/message_item.dart
lib/src/settings/settings_encryption.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/widgets/audio_visualizer.dart
lib/src/widgets/dialog_builder.dart
lib/src/widgets/profile_body.dart
lib/src/widgets/settings_item.dart

Fixes #534 
- SettingsItem didn't enforce a chevron setting
- Used non-adaptive dialogs
- Unnecessary padding for the audio visualization after recording
- The SettingsItem now enforces a parameter for the chevron. We also discussed about a new widget, but as this is the only difference and making the parameter required is clean and readable, I just made it required and renamed it
- Used adaptive dialogs or even better our pre-build dialogs
- Remove the unneeded padding
- The confirmation dialog now supports text or child widgets
- Simplified the handling of SettingsItems taps. I just removed the extra mapping, as it wasn't helpful and only lead to …

UI optimizations #534

---

lib/src/utils/url_preview_cache.dart

Fixes #541 - Error in `UrlPreviewCache`
* Adds test if cache directory exists. If not, it will be created.

HOTFIX fixes case when path is missing

---

lib/src/chat/chat.dart
lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event_state.dart
lib/src/chatlist/chat_list_item.dart
lib/src/chatlist/invite_item.dart
lib/src/contact/contact_item.dart
lib/src/data/repository_stream_handler.dart
lib/src/l10n/l.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
lib/src/message/message_item_event_state.dart
lib/src/message/message_list.dart
lib/src/message/message_list_bloc.dart
lib/src/message/message_list_event_state.dart
lib/src/settings/settings_appearance.dart

Fixes #507
The message state was not always updated. Random behavior and missing messages in the chat view / message list view.
The `MessageListBloc` listens now globally to update events for messages and relays + replays those to interested parties. `MessageItemBlocs` aren't listening directly to message state updates anymore. This leads to less core listeners, reliable event handling (late registration within the MessageItemBloc lead to not handled events, resulting in missing states) and a less error prone approach in general. 
**Fixed in this ticket**
- State not updated (sending, sent, read)
- Flickering due to numerous loading cycles or multiple listeners
- Wrong long …

Message state is not always updated OT-787 #507

---

lib/src/background_refresh/background_refresh_manager.dart
lib/src/data/repository_manager.dart
lib/src/l10n/l.dart
lib/src/notifications/local_notification_manager.dart
lib/src/platform/preferences.dart

Fixed #447
Notifications were created multiple times for multiple reasons.
We only had a temporary solution to track already shown notifications. Now using the shared preferences / user defaults allows us to persist the notification history. This also simplifies checks if a notification should be shown or not (the general flow is now just `isNewMessageIdOfChatOrInvite > savedMessageId`).
Added typing via generics to our RepositoryManager (not applied throughout the app, will be done later, as I tried to minimize the code impact of this ticket)

Duplicated notifications #447 OT-715

---

lib/src/brandable/brandable_icon.dart
lib/src/chatlist/invite_item.dart
lib/src/extensions/numbers_apis.dart
lib/src/gallery/gallery.dart
lib/src/gallery/gallery_bloc.dart
lib/src/gallery/gallery_event_state.dart
lib/src/l10n/l.dart
lib/src/message/message_attachment_bloc.dart
lib/src/message/message_attachment_event_state.dart
lib/src/message/message_builder.dart
lib/src/message/message_item.dart
lib/src/message/message_item_bloc.dart
pubspec.lock
pubspec.yaml
test/utils/date.dart

https://github.com/open-xchange/ox-coi/issues/251
At the moment the user has to choose another app to see videos, images and gifs. This should be fixed by an in-app gallery view.
Added the new gallery view for videos, images and gifs. The user can swipe left and right to go to the next media. When there is no more media a toast is shown.
- Added a new icon (pause)
- Added a new date format (formatterDateLongAndTime)
- Raised the version of the video_player plugin
**The iOS part in the core plugin needs to be added before merge.**
https://github.com/open-xchange/flutter-deltachat-core/pull/84

Show photos and videos in app #251

---

lib/main.dart
lib/src/login/login.dart
lib/src/login/login_events_state.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_list.dart
lib/src/login/login_provider_signin.dart
lib/src/main/root.dart
lib/src/ui/animations.dart
lib/src/ui/dimensions.dart
lib/src/widgets/fullscreen_progress.dart
lib/src/widgets/view_switcher.dart

https://github.com/open-xchange/ox-coi/issues/562
After a successful login the screen jumps to the first login page and then to the next one (onboarding). The correct way is to go directly to the next page.
The `login.dart` listens to the `MainStateSuccess` and after this the navigation stack is cleared.
- Cleaned up the login pages
- Removed unused listeners
- Removed methods that return a Widget

Login screen visible after successful login #562

---

lib/src/chat/chat_profile_group.dart
lib/src/chat/chat_profile_single.dart
lib/src/customer/customer.dart

Fixes https://github.com/open-xchange/ox-coi/issues/572
The notification settings button in the chat profiles is misleading and should be removed.
Removed the button from the chat profiles.
Fixed that the `settings_notifications.dart` is always empty. Reason: COI settings
```
_isCoiEnabled = (await Context().isCoiSupported()) == 1;
_isCoiSupported = (await Context().isCoiSupported()) == 1;
```
were not loaded after normal start.

Remove Notifications Setting from Chat Profile #572

---

pubspec.lock
pubspec.yaml

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-826)
The underlying library had an error.
The library is already fixed on the master branch, but there is no release yet. I just switched to our fork (https://github.com/open-xchange/metadata_fetch), which is exactly the same as the upstream master.

OT-826 Copied link will not be sent

---

lib/src/chat/chat_bloc.dart
lib/src/chat/chat_event_state.dart
lib/src/chat/chat_profile.dart
lib/src/chat/chat_profile_group.dart
lib/src/contact/contact_change_bloc.dart

Fixes #565 and [internal bug tracker 1](https://jira.open-xchange.com/browse/OT-828) + [internal bug tracker 2](https://jira.open-xchange.com/browse/OT-832)
- Group name was not updated in the profile view and the chat title after editing the group chat via the chat profile view
- Chat name was not updated after editing the contact via the chat profile view
The general problem was the change to generator methods (`yield*` / `async*`), which in general is good, but we used it wrong. A `yield*` call must stay in the `mapEventToState` method, so other callers must issue events to trigger the method, where then the correct handling is applied.
- Now adding the `UpdateChat`event …

Fix chat and profile not updating #565 OT-828 OT-832

---

test_driver/setup/helper_methods.dart

#554 
Sometimes the message test is unreliable. It fails during long press actions on mails.
Timeout added in flaggedMessage() function.

Message test unreliable #554

---

lib/src/adaptive_widgets/adaptive_bottom_sheet.dart
lib/src/adaptive_widgets/adaptive_bottom_sheet_action.dart
lib/src/adaptive_widgets/adaptive_dialog.dart
lib/src/adaptive_widgets/adaptive_dialog_action.dart
lib/src/chat/chat.dart
lib/src/contact/contact_change.dart
lib/src/contact/contact_item.dart
lib/src/contact/contact_list.dart
lib/src/customer/customer_delegate.dart
lib/src/login/login_manual_settings.dart
lib/src/login/login_provider_signin.dart
lib/src/main/root.dart
lib/src/message/message_item.dart
lib/src/navigation/navigatable.dart
lib/src/settings/settings_encryption.dart
lib/src/user/user_account_settings.dart
lib/src/user/user_profile.dart
lib/src/utils/keyMapping.dart
lib/src/widgets/modal_builder.dart
lib/src/widgets/profile_body.dart
lib/src/widgets/profile_header.dart

Fixed #589 
We used the bottom sheet on Android and iOS, but on iOS the native action sheet should be used.
- Created a new adaptive widget using the bottom sheet on Android and the action sheet on iOS.
- Applied the new widget (Onboarding, profile, add attachment)
- Small renaming
- On Android everything should just look the same and behave the same
- On iOS the UI for modal bottom popups should be more native now

Profile picture can't be deleted #589 OT-843

---

lib/src/dynamic_screen/widgets/page_components/page_textfield_component.dart

Fixes #588 
- Username deleted when selecting avatar after setting the name
- Username deleted when choosing next and afterwards going back
Added the initial value to the widget.
- Removed unneeded components.

Onboarding deletes profile name if screen is changed #588 OT-842

---

lib/src/chat/chat_create.dart

It was not possible to create a chat over the "ChatCreate.dart" view.
Added the missing `contactItemType: ContactItemType.createChat` to the `ContactListContent` widget.

HOTFIX: Tap contact on create chat view is not working
